apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-gke-tsb
  namespace: tsb
spec:
  acme:
    email: xxxxx
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-issuer-gke-tsb-account-key
    solvers:
    - selector:
        dnsZones:
          - "xxxxx"
      dns01:
        cloudDNS:
          project: xxxx
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tsb-certs
  namespace: tsb
spec:
  secretName: tsb-certs
  issuerRef:
    name: letsencrypt-gke-tsb
    kind: ClusterIssuer
  dnsNames:
  - xxxx