---
apiVersion: install.tetrate.io/v1alpha1
kind: ManagementPlane
metadata:
  namespace: tsb
  name: tsbmgmtplane
spec:
  hub: xxxx
  organization: tetrate
  components:
    apiServer:
      teamSyncSchedule: 0 * * * *
    frontEnvoy:
      port: 443
  dataStore:
    postgres:
      host: xxx
      port: 5432
      name: postgres
      sslMode: prefer