---
apiVersion: v1
kind: Namespace
metadata:
  name: t1
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: tsb-tier1
  namespace: t1
spec:
  kubeSpec:
    service:
      type: LoadBalancer
