apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate
  workspace: bookinfo-workspace
  name: bookinfo-gateway
spec:
  displayName: bookinfo-gateway
  description: bookinfo-gateway
  namespaceSelector:
    names:
      - "gke1-cluster/bookinfo"
      - "gke2-cluster/bookinfo"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate
  workspace: bookinfo-workspace
  name: bookinfo-tier1
spec:
  displayName: bookinfo-tier1
  description: bookinfo-tier1
  namespaceSelector:
    names:
      - "mgmt-cluster/t1"
  configMode: BRIDGED
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: bookinfo-gw
  group: bookinfo-gateway
  workspace: bookinfo-workspace
  tenant: tetrate
spec:
  workloadSelector:
    namespace: bookinfo
    labels:
      app: tsb-gateway-bookinfo
  http:
    - name: bookinfo-gw
      port: 443
      hostname: xxxx
      tls:
        mode: SIMPLE
        secretName: bookinfo-certs
      routing:
        rules:
          - route:
              host: "bookinfo/productpage.bookinfo.svc.cluster.local"
              port: 9080
    - name: details-gw
      port: 9080
      hostname: "details.mesh.local"
      tls:
        mode: SIMPLE
        secretName: bookinfo-certs
      routing:
        rules:
          - route:
              host: "bookinfo/details.bookinfo.svc.cluster.local"
              port: 9080
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Tier1Gateway
metadata:
  name: bookinfo-tier1
  group: bookinfo-tier1
  workspace: bookinfo-workspace
  tenant: tetrate
spec:
  workloadSelector:
    namespace: t1
    labels:
      app: tsb-tier1
  externalServers:
  - hostname: xxxx
    name: bookinfo
    port: 443
    tls:
      mode: SIMPLE
      secretName: bookinfo-certs
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  tenant: tetrate
  workspace: bookinfo-workspace
  name: bookinfo-security
spec:
  displayName: bookinfo-security
  description: bookinfo-security
  namespaceSelector:
    names:
    - "*/bookinfo"
  configMode: BRIDGED