---
apiVersion: networking.istio.io/v1alpha3
kind: WorkloadEntry
metadata:
  name: ratings-vm
  namespace: bookinfo
  annotations:
    sidecar-bootstrap.istio.io/ssh-host: 34.73.147.79
    sidecar-bootstrap.istio.io/ssh-user: zwickey
    sidecar-bootstrap.istio.io/proxy-config-dir: /etc/istio-proxy
    sidecar-bootstrap.istio.io/proxy-image-hub: docker.io/tetrate
    sidecar-bootstrap.istio.io/proxy-instance-ip: 10.142.0.50
spec:
  address: 10.142.0.50
  labels:
    cloud: gcp
    class: vm
    app: ratings
    version: v2
  serviceAccount: default
  #network: gcp
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: gcp-ratings-no-iptables
  namespace: bookinfo
spec:
  workloadSelector:
    labels:
      cloud: gcp
      class: vm           # to avoid interfering with configuration of sidecars on k8s 
      app: ratings
  ingress:
  - port:
      number: 9080
      protocol: HTTP
      name: http
    defaultEndpoint: 127.0.0.1:9080
  egress:
  - bind: 127.0.0.2
    hosts:
    - "./*"