apiVersion: api.tsb.tetrate.io/v2
kind: WorkspaceSetting
metadata:
  displayName: bookinfo-baseline
  name: bookinfo-baseline
  organization: tetrate
  tenant: tetrate
  workspace: bookinfo-workspace
spec:
  defaultTrafficSetting:
    fqn: fqn#
    resilience:
      circuitBreakerSensitivity: MEDIUM
  regionalFailover:
  - from: us-east1      
    to: us-west1
  displayName: bookinfo-baseline

